# Generated by Django 3.2.7 on 2021-09-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('management_ip', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('vlan_tag', models.CharField(max_length=4, unique=True)),
                ('network_address', models.CharField(max_length=18, unique=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.router')),
            ],
        ),
    ]
