# Generated by Django 3.2.7 on 2021-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='os_type',
            field=models.CharField(choices=[('Linux', 'Linux'), ('IOS', 'Cisco IOS'), ('JunOS', 'Juniper JunOS')], default=('Linux', 'Linux'), max_length=50),
        ),
    ]
