# Generated by Django 3.2.7 on 2021-09-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_router_os_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='gateway',
            new_name='router',
        ),
    ]
